Repository woori-fisa-ai-final/AI-Chat-Bot-Proj, pull requests merged in 2024-12, with the labels that each got.

#445 history 생성
  project/WEB/authenticate/urls.py
  project/WEB/authenticate/views.py
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/templates/tmp_origin.html
  project/WEB/chatbot/urls.py
  project/WEB/chatbot/views_chatbot.py
  project/WEB/staticfiles/js/history.js
  project/WEB/woodjango/settings.py
Labels: ✅ 됐다!

#455 main.html -> trend 지수 예측 update
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/views/views_main.py
  project/WEB/chatbot/views/views_trend.py
  project/WEB/staticfiles/js/dashboard.js
Labels: ✅ 됐다!

#456 setting.py csrf권한 수정
  project/WEB/woodjango/settings.py
Labels: ✅ 됐다!

#461 챗봇 프롬포트 수정
  project/WEB/chatbot/views/views_chatbot.py
Labels: ✅ 됐다!

#463 logout update
  project/WEB/authenticate/views.py
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/views/views_hoseop.py
Labels: 🚧 기능 개발

#474 챗봇 고도화 해봄
  project/WEB/chatbot/views/views_chatbot.py
Labels: 🔧 개발 중

#476 thumb's up 수정중
  project/WEB/authenticate/views.py
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/urls.py
  project/WEB/chatbot/views/views_chatbot.py
  project/WEB/staticfiles/js/chatbot.js
Labels: 🚧 기능 개발

#479 챗봇고도화 -프롬포트 수정
  project/WEB/chatbot/views/views_chatbot.py
Labels: ✅ 됐다!

#484 csrf랑 마이그레이션 git ignore
  .gitignore
  project/WEB/authenticate/views.py
Labels: ✅ 됐다!

#488 장고 도커파일 수정
  project/WEB/dockerfile
Labels: ✅ 됐다!

#491 색변경
  project/WEB/chatbot/views/views_indicator.py
Labels: ✅ 됐다!

#492 default 질의 생성
  project/WEB/chatbot/views/views_chatbot.py
  project/WEB/staticfiles/js/chatbot.js
  project/WEB/staticfiles/js/history.js
Labels: ✅ 됐다!

#504 revise architecture
  README.md
Labels: 📖 문서 작성
