Repository woori-fisa-ai-final/AI-Chat-Bot-Proj, pull requests merged in 2024-10, with the labels that each got.

#5 #3 깃 컨벤션 공유
  Manual/git.md
  Manual/gitConvention.md
  README.md
Labels: 📖 문서 작성

#7 image err fix
  .DS_Store
  Manual/.DS_Store
  Manual/git.md
  Manual/images/branch_(0).png
  Manual/images/branch_(1).png
  Manual/images/branch_(2).png
  Manual/images/branch_(3).png
  Manual/images/branch_(4).png
  Manual/images/branch_(5).png
  Manual/images/branch_(6).png
  Manual/images/issue_0.png
  Manual/images/issue_1.png
  Manual/images/issue_2.png
  Manual/images/issue_3.png
  Manual/images/issue_4.png
  Manual/images/issue_5.png
  Manual/images/issue_6.png
  Manual/images/issue_7.png
  Manual/images/merge_0.png
  Manual/images/merge_1.png
  Manual/images/merge_2.png
  Manual/images/merge_3.png
  Manual/images/merge_4.png
  Manual/images/merge_5.png
Labels: 🐛 버그 🐛, 📖 문서 작성, ✅ 됐다!

#9 diagrams and documents
  .DS_Store
  .gitignore
  Manual/.DS_Store
  diagrams/airflow.png
  diagrams/diagrams.pptx
  diagrams/diagrams/슬라이드1.png
  diagrams/diagrams/슬라이드2.png
  diagrams/diagrams/슬라이드3.png
  diagrams/structure.png
Labels: 📖 문서 작성, ✅ 됐다!

#11 [Docs] change and modify directory trees
  Documents/Manual/git.md
  Documents/Manual/gitConvention.md
  Documents/Manual/images/branch_(0).png
  Documents/Manual/images/branch_(1).png
  Documents/Manual/images/branch_(2).png
  Documents/Manual/images/branch_(3).png
  Documents/Manual/images/branch_(4).png
  Documents/Manual/images/branch_(5).png
  Documents/Manual/images/branch_(6).png
  Documents/Manual/images/issue_0.png
  Documents/Manual/images/issue_1.png
  Documents/Manual/images/issue_2.png
  Documents/Manual/images/issue_3.png
  Documents/Manual/images/issue_4.png
  Documents/Manual/images/issue_5.png
  Documents/Manual/images/issue_6.png
  Documents/Manual/images/issue_7.png
  Documents/Manual/images/merge_0.png
  Documents/Manual/images/merge_1.png
  Documents/Manual/images/merge_2.png
  Documents/Manual/images/merge_3.png
  Documents/Manual/images/merge_4.png
  Documents/Manual/images/merge_5.png
  Documents/diagrams/airflow.png
  Documents/diagrams/diagrams.pptx
  Documents/diagrams/diagrams/슬라이드1.png
  Documents/diagrams/diagrams/슬라이드2.png
  Documents/diagrams/diagrams/슬라이드3.png
  Documents/diagrams/structure.png
  README.md
Labels: 📖 문서 작성, ✅ 됐다!

#13 success connect
  ddd/dd
Labels: 🚧 기능 개발, ✅ 됐다!

#14 12 connect api_FredAPI
  .gitignore
  Documents/Manual/git.md
  Documents/Manual/gitConvention.md
  Documents/Manual/images/branch_(0).png
  Documents/Manual/images/branch_(1).png
  Documents/Manual/images/branch_(2).png
  Documents/Manual/images/branch_(3).png
  Documents/Manual/images/branch_(4).png
  Documents/Manual/images/branch_(5).png
  Documents/Manual/images/branch_(6).png
  Documents/Manual/images/issue_0.png
  Documents/Manual/images/issue_1.png
  Documents/Manual/images/issue_2.png
  Documents/Manual/images/issue_3.png
  Documents/Manual/images/issue_4.png
  Documents/Manual/images/issue_5.png
  Documents/Manual/images/issue_6.png
  Documents/Manual/images/issue_7.png
  Documents/Manual/images/merge_0.png
  Documents/Manual/images/merge_1.png
  Documents/Manual/images/merge_2.png
  Documents/Manual/images/merge_3.png
  Documents/Manual/images/merge_4.png
  Documents/Manual/images/merge_5.png
  Documents/diagrams/airflow.png
  Documents/diagrams/diagrams.pptx
  Documents/diagrams/diagrams/슬라이드1.png
  Documents/diagrams/diagrams/슬라이드2.png
  Documents/diagrams/diagrams/슬라이드3.png
  Documents/diagrams/structure.png
  README.md
  dashboard_feature/Macro_requirements.txt
  dashboard_feature/Macroeconomic_Indicators_Data.py
Labels: 🚧 기능 개발, ✅ 됐다!

#15 Revert 14 12 connect api
  .gitignore
  Documents/Manual/git.md
  Documents/Manual/gitConvention.md
  Documents/Manual/images/branch_(0).png
  Documents/Manual/images/branch_(1).png
  Documents/Manual/images/branch_(2).png
  Documents/Manual/images/branch_(3).png
  Documents/Manual/images/branch_(4).png
  Documents/Manual/images/branch_(5).png
  Documents/Manual/images/branch_(6).png
  Documents/Manual/images/issue_0.png
  Documents/Manual/images/issue_1.png
  Documents/Manual/images/issue_2.png
  Documents/Manual/images/issue_3.png
  Documents/Manual/images/issue_4.png
  Documents/Manual/images/issue_5.png
  Documents/Manual/images/issue_6.png
  Documents/Manual/images/issue_7.png
  Documents/Manual/images/merge_0.png
  Documents/Manual/images/merge_1.png
  Documents/Manual/images/merge_2.png
  Documents/Manual/images/merge_3.png
  Documents/Manual/images/merge_4.png
  Documents/Manual/images/merge_5.png
  Documents/diagrams/airflow.png
  Documents/diagrams/diagrams.pptx
  Documents/diagrams/diagrams/슬라이드1.png
  Documents/diagrams/diagrams/슬라이드2.png
  Documents/diagrams/diagrams/슬라이드3.png
  Documents/diagrams/structure.png
  README.md
  ddd/dd
Labels: 🐛 버그 🐛, ✅ 됐다!

#18 elk stack docker files added
  elk_stack/docker-compose.yml
Labels: 🚧 기능 개발, ✅ 됐다!

#21 dockerfile 만들었음
  sukbeom/dockerfile
Labels: 🚧 기능 개발, ✅ 됐다!

#25 first try2
  eunji/ㅎㅎㅎ
Labels: 🐛 버그 🐛

#27 hi
  hoseop/hello.py
Labels: ✅ 됐다!

#29 기존 작업물
  eunchai/1.py
  eunchai/docker-compose.yml
  eunchai/index_data.py
  eunchai/lda_visualization.html
  eunchai/naver_news.py
  eunchai/topic_model.py
  eunchai/topic_modeling_results.json
  eunchai/오늘 날씨_naver_news.json
  eunchai/카드 상품_naver_news.json
Labels: 🚧 기능 개발, ✅ 됐다!

#31 docker files that runs airflow and kafka
  .gitignore
  elk_stack/docker-compose.yml
  sukbeom/airflow/docker-compose.yaml
  sukbeom/airflow/logs/scheduler/latest
  sukbeom/kafka/docker-compose.yaml
  sukbeom/kafka/kafka.sh
Labels: 🚧 기능 개발, ✅ 됐다!

#35 elasticsearch success
  jinwon/fisa-airflow/Dockerfile
  jinwon/fisa-airflow/README.md
  jinwon/fisa-airflow/dags/D_01_Freddata_sql.py
  jinwon/fisa-airflow/dags/D_02_Freddata_elk.py
  jinwon/fisa-airflow/dags/plugins/file_ops.py
  jinwon/fisa-airflow/dags/plugins/gsheet.py
  jinwon/fisa-airflow/dags/plugins/redshift.py
  jinwon/fisa-airflow/dags/plugins/redshift_summary.py
  jinwon/fisa-airflow/dags/plugins/s3.py
  jinwon/fisa-airflow/dags/plugins/s3_to_redshift_operator.py
  jinwon/fisa-airflow/dags/plugins/slack.py
  jinwon/fisa-airflow/data/jinja.sh
  jinwon/fisa-airflow/docker-compose.yaml
  jinwon/fisa-airflow/pythonapi/fredapi.py
  jinwon/fisa-airflow/pythonapi/requiremenets.txt
  jinwon/mysql/docker-compose.yml
Labels: ✅ 됐다!

#38 upload file
  hoseop/CPI_PCE_시계열예측.ipynb
  hoseop/hello.py
Labels: 🚧 기능 개발

#40 37 입법예고규정변경예고 크롤링 1
  eunji/data_extract/fsc_announcements.csv
  eunji/data_extract/fsc_announcements_crawling.py
  eunji/data_extract/fsc_announcements_extract.csv
  eunji/data_extract/fsc_extract_content.py
  eunji/data_extract/fsc_summury.py
  eunji/data_extract/requirements.txt
  eunji/ㅎㅎㅎ
Labels: 🔧 개발 중

#42 39 kibana plugin develop
  .gitignore
  jinwon/ELK/docker-compose.yml
  jinwon/docker-compose.yml
  jinwon/mysql/docker-compose.yml
  sukbeom/airflow/Dockerfile
  sukbeom/airflow/README.md
  sukbeom/airflow/airflow.sh
  sukbeom/airflow/dags/D_01_Freddata_sql.py
  sukbeom/airflow/dags/D_02_Freddata_elk.py
  sukbeom/airflow/dags/plugins/file_ops.py
  sukbeom/airflow/dags/plugins/gsheet.py
  sukbeom/airflow/dags/plugins/redshift.py
  sukbeom/airflow/dags/plugins/redshift_summary.py
  sukbeom/airflow/dags/plugins/s3.py
  sukbeom/airflow/dags/plugins/s3_to_redshift_operator.py
  sukbeom/airflow/dags/plugins/slack.py
  sukbeom/airflow/data/jinja.sh
  sukbeom/airflow/docker-compose.yaml
  sukbeom/airflow/logs/scheduler/latest
  sukbeom/airflow/pythonapi/fredapi.py
  sukbeom/airflow/pythonapi/requiremenets.txt
  sukbeom/integrated_docker/docker-compose.yml
  sukbeom/integrated_docker/requirements.txt
Labels: 🚧 기능 개발, ✅ 됐다!

#46 45 merge conflict solving
  .gitignore
  Documents/references/idea.md
  sukbeom/backend/mvp.ipynb
  sukbeom/dockerfile
  sukbeom/integrated_docker/requirements.txt
Labels: 🐛 버그 🐛, ✅ 됐다!

#49 env추가
  .gitignore
  jinwon/fisa-airflow/dags/D_02_Freddata_elk.py
Labels: ✅ 됐다!

#50 misc
  sukbeom/backend/mvp.ipynb
  sukbeom/integrated_docker/requirements.txt
Labels: 🐛 버그 🐛

#51 fsc dag
  eunji/data_extract/fsc_announcements.csv
  eunji/data_extract/fsc_crawling_to50.py
  eunji/data_extract/fsc_crawling_toend.py
  eunji/data_extract/try.py
  jinwon/fisa-airflow/dags/fsc_all.py
  jinwon/fisa-airflow/dags/fsc_announcements_extract.csv
  jinwon/fisa-airflow/dags/fsc_crawling.py
  jinwon/fisa-airflow/dags/fsc_daily.py
  jinwon/fisa-airflow/dags/fsc_extract.py
Labels: ✅ 됐다!
