Repository woori-fisa-ai-final/AI-Chat-Bot-Proj, pull requests merged in 2024-11, with the labels that each got.

#76 Shell script and docker files added
  deploy.sh
  project/DB/airflow/docker-compose.yaml
  project/WEB/docker-compose.yml
  project/WEB/dockerfile
  requirements.txt
Labels: 🚧 기능 개발, 🔧 개발 중

#78 1104 조진원 작업
  .gitignore
  project/DB/airflow/dags/EC_01_run_python_files_dag.py
  project/DB/airflow/dags/E_01_fsc_csv.py
  project/DB/airflow/dags/E_02_fsc_daily.py
  project/DB/airflow/dags/E_03_fsc_first.py
  project/DB/airflow/dags/H_01_cpi_pce.py
  project/FISA/__init__.py
  project/FISA/eunchai/__init__.py
  project/FISA/eunji/__init__.py
  project/FISA/hoseop/__init__.py
  project/FISA/jinwon/__init__.py
  project/FISA/jiyeon/__init__.py
  project/FISA/sukbeom/__init__.py
  project/WEB/chatbot/templates/index.html
Labels: 🔧 개발 중

#79 deploy.sh 고쳤음
  deploy.sh
Labels: 🐛 버그 🐛, ✅ 됐다!

#92 airflow 코드 수정중
  project/DB/airflow/__init__.py
  project/DB/airflow/dags/D_02_Freddata_elk.py
  project/DB/airflow/dags/E_01_fsc_csv.py
  project/DB/airflow/dags/E_02_fsc_daily.py
  project/DB/airflow/dags/E_03_fsc_first.py
  project/DB/airflow/dags/H_01_cpi_pce.py
  project/DB/airflow/dags/__init__.py
  project/DB/airflow/dags/package/__init__.py
  project/DB/airflow/dags/package/fsc_crawling.py
  project/DB/airflow/dags/package/fsc_extract.py
  project/DB/airflow/docker-compose.yaml
  project/FISA/eunji/fsc_crawling copy.py
  project/FISA/eunji/fsc_extract copy.py
  project/WEB/requirements.txt
Labels: 🐛 버그 🐛

#90 dashboard_macro add
  project/DB/airflow/docker-compose.yaml
  project/FISA/jiyeon/dashboard_macro_fred_ecos.py
  requirements.txt
Labels: 🔧 개발 중

#100 98 deploy shell script change
  deploy.sh
Labels: ✅ 됐다!

#106 수정
  project/DB/airflow/dags/D_01_Freddata_sql.py
  project/DB/airflow/dags/E_03_fsc_first.py
Labels: 🔧 개발 중

#107 마지막 airflow 오류..(제발)
  project/DB/airflow/dags/EC_01_run_python_files_dag.py
Labels: ✅ 됐다!

#110 done
  Documents/diagrams/diagrams.pptx
  Documents/diagrams/system_diagrams.png
Labels: 📖 문서 작성, ✅ 됐다!

#113 embedding -ing
  project/DB/airflow/Dockerfile
  project/DB/airflow/dags/E_03_fsc_first.py
  project/DB/airflow/dags/package/vector_embedding.py
  project/WEB/woodjango/settings.py
Labels: 🔧 개발 중

#115 vector db
  project/DB/airflow/dags/E_02_fsc_daily.py
  project/DB/airflow/dags/E_03_fsc_first.py
  project/DB/airflow/dags/package/vector_embedding.py
Labels: ✅ 됐다!

#116 add
  Documents/diagrams/systemArchitecture.drawio
  Documents/diagrams/systemArchitecture2.drawio.png
Labels: 📖 문서 작성, ✅ 됐다!

#129 로그인 창 생성 및 db는 일단 로컬 연결
  project/WEB/authenticate/admin.py
  project/WEB/authenticate/apps.py
  project/WEB/authenticate/forms.py
  project/WEB/authenticate/models.py
  project/WEB/authenticate/templates/authenticate/base.html
  project/WEB/authenticate/templates/authenticate/change_password.html
  project/WEB/authenticate/templates/authenticate/edit_profile.html
  project/WEB/authenticate/templates/authenticate/login.html
  project/WEB/authenticate/templates/authenticate/register.html
  project/WEB/authenticate/tests.py
  project/WEB/authenticate/urls.py
  project/WEB/authenticate/views.py
  project/WEB/woodjango/settings.py
  project/WEB/woodjango/urls.py
Labels: 🔧 개발 중

#131 fisaai db 연동
  project/WEB/db.sqlite3
  project/WEB/requirements.txt
  project/WEB/woodjango/settings.py
Labels: ✅ 됐다!

#147 136 readme update
  project/DB/ELK/docker-compose.yml
  project/FISA/sukbeom/openSearch/docker-compose.yml
  project/FISA/sukbeom/openSearch/opensearch.yml
Labels: 🚧 기능 개발, ✅ 됐다!

#150 add
  .gitignore
Labels: ✅ 됐다!

#157 airflow 버그 해결
  project/DB/airflow/dags/D_02_Freddata_elk.py
  project/DB/airflow/dags/EC_01_run_python_files_dag.py
  project/DB/airflow/dags/H_01_cpi_pce.py
Labels: 🐛 버그 🐛

#159 modded
  project/DB/ELK/docker-compose.yml
Labels: ✅ 됐다!

#160 엘라스틱 저장 + nori 설치
  project/DB/ELK/docker-compose.yml
Labels: ✅ 됐다!

#163 es_service 수정
  project/WEB/dashboards/es_service.py
Labels: 🐛 버그 🐛

#164 elk docker 수정
  project/DB/ELK/docker-compose.yml
Labels: 🐛 버그 🐛

#166 connect to opensearch
  project/DB/airflow/Dockerfile
  project/DB/airflow/docker-compose.yaml
  project/FISA/sukbeom/ipynb/test.ipynb
Labels: 🚧 기능 개발, 🔧 개발 중

#167 gitignore
  .gitignore
Labels: 🐛 버그 🐛

#168 dag change
  project/DB/airflow/dags/D_02_Freddata_elk.py
  project/DB/airflow/dags/EC_01_run_python_files_dag.py
  project/DB/airflow/dags/E_01_fsc_csv.py
  project/DB/airflow/dags/E_02_fsc_daily.py
  project/DB/airflow/dags/E_03_fsc_first embedding.py
  project/DB/airflow/dags/E_03_fsc_first.py
  project/DB/airflow/dags/E_04_raw_url.py
  project/DB/airflow/dags/H_01_cpi_pce.py
Labels: 🚧 기능 개발, 🔧 개발 중

#169 dag import error fixed
  project/DB/airflow/dags/EC_01_run_python_files_dag.py
  project/DB/airflow/dags/E_01_fsc_csv.py
  project/DB/airflow/dags/E_02_fsc_daily.py
  project/DB/airflow/dags/E_03_fsc_first embedding.py
  project/DB/airflow/dags/E_03_fsc_first.py
  project/DB/airflow/dags/H_01_cpi_pce.py
  project/FISA/sukbeom/openSearch/settings/rag_chat.sh
Labels: 🐛 버그 🐛, ✅ 됐다!, 🔧 개발 중

#171 dags to opensearch
  project/DB/airflow/dags/D_02_Freddata_elk.py
  project/DB/airflow/dags/EC_01_run_python_files_dag.py
  project/DB/airflow/dags/E_01_fsc_csv.py
  project/DB/airflow/dags/E_02_fsc_daily.py
  project/DB/airflow/dags/E_03_fsc_first embedding.py
  project/DB/airflow/dags/E_03_fsc_first.py
  project/DB/airflow/dags/E_04_raw_url.py
  project/DB/airflow/dags/H_01_cpi_pce.py
Labels: 🚧 기능 개발, 🔧 개발 중

#172 add pandas_to_opensearch
  project/DB/airflow/Dockerfile
  project/DB/airflow/dags/D_02_Freddata_elk.py
  project/DB/airflow/dags/E_01_fsc_csv.py
  project/DB/airflow/dags/E_03_fsc_first.py
  project/DB/airflow/dags/H_01_cpi_pce.py
Labels: 🚧 기능 개발, 🔧 개발 중

#173 dense_ to knn
  project/DB/airflow/dags/E_03_fsc_first embedding.py
Labels: 🚧 기능 개발, 🔧 개발 중

#176 add opensearch to DB
  project/DB/openSearch/docker-compose.yml
  project/DB/openSearch/opensearch.yml
  project/FISA/sukbeom/openSearch/settings/rag_chat.sh
Labels: 🚧 기능 개발, ✅ 됐다!

#177 OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m
  project/DB/openSearch/docker-compose.yml
Labels: 🚧 기능 개발, ✅ 됐다!

#181 django fix
  project/WEB/chatbot/langchain.py
  project/WEB/chatbot/templates/index.html
  project/WEB/chatbot/views.py
  project/WEB/dashboards/es_service.py
  project/WEB/requirements.txt
Labels: 🚧 기능 개발, 🔧 개발 중

#182 Dag refresh
  project/DB/airflow/dags/01_Fred_data.py
  project/DB/airflow/dags/02_fsc_first.py
  project/DB/airflow/dags/03_fsc_daily.py
  project/DB/airflow/dags/04_raw_url.py
  project/DB/airflow/dags/05_run_python_files_dag.py
  project/DB/airflow/dags/06_cpi_pce.py
  project/DB/airflow/dags/07_cuurency_rate_first.py
Labels: 🔧 개발 중

#195 test file
  project/FISA/sukbeom/embedding.py
Labels: 🚧 기능 개발, 🔧 개발 중

#197 dag_embedding_code
  project/DB/airflow/dags/01_Fred_data.py
Labels: 🔧 개발 중

#200 embedding still in progress
  project/DB/airflow/dags/04_raw_url.py
  project/DB/airflow/dags/J_01_card_data.py
Labels: 🚧 기능 개발, 🔧 개발 중

#208 add jupyter compose file and sample ipynb
  project/FISA/sukbeom/Playground/docker-compose.yml
  project/Playground/docker-compose.yml
  project/Playground/jupyter/sukbeom/05.rag.ipynb
  project/Playground/jupyter/sukbeom/openai-KNN-RAG.ipynb
Labels: 🚧 기능 개발, ✅ 됐다!, 🔧 개발 중

#212 210 django add iframe
  .gitignore
  project/DB/openSearch/docker-compose.yml
  project/DB/openSearch/opensearch_dashboards.yml
  project/WEB/chatbot/templates/index.html
Labels: 🐛 버그 🐛, 🚧 기능 개발, 🔧 개발 중

#215 test dags
  project/DB/airflow/Dockerfile
  project/DB/airflow/dags/testetest.py
Labels: 🚧 기능 개발, 🔧 개발 중

#216 우리카드 데이터 업로드
  project/DB/airflow/dags/06_cpi_pce.py
  project/DB/airflow/dags/H_01_wooricard_data.py
  project/DB/airflow/data/wooricard_data/age_payment.csv
  project/DB/airflow/data/wooricard_data/female_expense.csv
  project/DB/airflow/data/wooricard_data/male_expense.csv
  project/DB/airflow/data/wooricard_data/region_consumption.csv
  project/DB/airflow/data/wooricard_data/top10_level_categories.csv
  project/DB/airflow/data/wooricard_data/top_age_categories.csv
Labels: ✅ 됐다!

#218 git ignore
  .gitignore
Labels: 📖 문서 작성, 🔧 개발 중

#219 web reqiurements txt file update
  project/WEB/requirements.txt
Labels: 🔧 개발 중

#223 dag 이름 수정
  project/DB/airflow/dags/H_01_wooricard_data.py
Labels: 🔧 개발 중

#229 dag 찐 수정
  project/DB/airflow/dags/H_01_wooricard_data.py
Labels: 🔧 개발 중

#232 index-mapping int->integer
  project/DB/airflow/dags/H_01_wooricard_data.py
Labels: 🔧 개발 중

#234 228 dag 진짜 수정
  project/DB/airflow/data/wooricard_data/region_consumption.csv
Labels: ✅ 됐다!

#238 14일 아침
  project/DB/airflow/dags/01_Fred_data.py
  project/DB/airflow/dags/J_02_franchise.py
Labels: 🚧 기능 개발

#246 django updated by cursor
  project/WEB/chatbot/templates/index.html
  project/WEB/chatbot/urls.py
  project/WEB/chatbot/views.py
  project/WEB/woodjango/urls.py
Labels: 🚧 기능 개발, 🔧 개발 중

#255 H_01_wooricard_data.py 수정
  project/DB/airflow/dags/H_01_wooricard_data.py
Labels: 🐛 버그 🐛

#271 sql 모델 연동
  project/WEB/chatbot/admin.py
  project/WEB/chatbot/models.py
  project/WEB/woodjango/settings.py
Labels: 🚧 기능 개발

#276 admin+models
  project/WEB/chatbot/admin.py
  project/WEB/chatbot/models.py
Labels: 🚧 기능 개발

#277 fix
  project/WEB/chatbot/templates/dashboard_hoseop.html
Labels: 🐛 버그 🐛

#279 dashboard_hoseop.py 파일 안의 데이터 db 연동했습니다.
  project/WEB/chatbot/views.py
  project/WEB/chatbot/views_hoseop.py
Labels: ✅ 됐다!

#280 chat overlay
  project/WEB/chatbot/templates/dashboard_hoseop.html
Labels: 🐛 버그 🐛, ✅ 됐다!

#288 frontend develop complete
  project/WEB/chatbot/templates/dashboard_hoseop.html
  project/WEB/chatbot/urls.py
  project/WEB/woodjango/settings.py
Labels: 🚧 기능 개발, ✅ 됐다!

#290 dag수정 1차
  project/DB/airflow/Dockerfile
  project/DB/airflow/dags/01_Fred_data.py
  project/DB/airflow/dags/07_cuurency_rate.py
  project/DB/airflow/dags/J_02_franchise.py
Labels: 🚧 기능 개발

#291 289 iframe fix - opensearch docker compose file fix
  .gitignore
  project/DB/openSearch/docker-compose.yml
  project/DB/openSearch/opensearch_dashboards.yml
  project/FISA/sukbeom/openSearch/Dockerfile_dashboard
  project/FISA/sukbeom/openSearch/Dockerfile_node
  project/FISA/sukbeom/openSearch/docker-compose.yml
  project/FISA/sukbeom/openSearch/opensearch.yml
  project/FISA/sukbeom/openSearch/opensearch_dashboards.yml
Labels: 🐛 버그 🐛, 🚧 기능 개발

#295 dag수정 2차
  project/DB/airflow/dags/EJ_Travel_Advices.py
  project/DB/airflow/dags/EJ_Travel_Cautions.py
Labels: 🔧 개발 중

#296 opensearch dag fix
  project/DB/airflow/dags/EJ_KAC_Intl_Flight_Schedule.py
  project/DB/airflow/dags/EJ_TOUR_INTRST.py
  project/DB/airflow/dags/EJ_Travel_naver_search_all.py
  project/DB/airflow/dags/H_01_wooricard_data.py
  project/DB/airflow/dags/J_01_card_data.py
  project/DB/airflow/dags/eunchai_trend.py
  project/FISA/hoseop/H_01_wooricard_data.py
Labels: 🐛 버그 🐛, 🚧 기능 개발, 🔧 개발 중

#299 add chatbot
  project/WEB/chatbot/views_chatbot.py
Labels: 🚧 기능 개발

#302 revise html
  project/WEB/chatbot/templates/dashboard_hoseop.html
Labels: 🐛 버그 🐛

#306 POWER MODEEEEEEE!!!!!!!!!!!!!!!!!!!!!!!!!!!
  project/FISA/sukbeom/ipynb/beautifulSoup.ipynb
  project/WEB/chatbot/templates/dashboard_hoseop.html
  project/WEB/chatbot/views_chatbot.py
Labels: 🚧 기능 개발, 🔧 개발 중

#307 revise dags
  project/DB/airflow/Dockerfile
  project/DB/airflow/dags/02_Korean_Law_data.py
  project/DB/airflow/dags/package/fsc_extract.py
  project/DB/airflow/dags/package/naver_news2.py
  project/DB/airflow/dags/package/topic_model3.py
  project/DB/airflow/dags/package/watching_word.py
  project/DB/airflow/dags/package/한국공항공사_국제선 항공기스케줄_20240809.csv
Labels: 🐛 버그 🐛

#309 changing django structure
  project/WEB/authenticate/views.py
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/urls.py
  project/WEB/chatbot/views.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_main.py
  project/WEB/woodjango/urls.py
Labels: 🔧 개발 중

#312 revise dags
  project/DB/airflow/dags/02_Korean_Law_data.py
  project/DB/airflow/dags/08_Travel_naver_search_all.py
Labels: 🐛 버그 🐛

#315 django update
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/views_chatbot.py
Labels: 🚧 기능 개발, 🔧 개발 중

#319 tmp파일 생성
  project/WEB/chatbot/templates/dashboard1.html
  project/WEB/chatbot/templates/index.html
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/urls.py
  project/WEB/chatbot/views_main.py
  project/WEB/woodjango/settings.py
Labels: 🚧 기능 개발

#322 tmp 수정
  project/WEB/authenticate/views.py
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/urls.py
  project/WEB/chatbot/views_card_sales.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_main.py
Labels: ✅ 됐다!

#328 장고 수정
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_main.py
Labels: ✅ 됐다!

#330 제발 되게해주세요
  project/WEB/authenticate/urls.py
  project/WEB/chatbot/views_hoseop.py
Labels: ✅ 됐다!

#334 fix done
  project/DB/airflow/dags/07_cuurency_rate.py
Labels: ✅ 됐다!

#342 dag modification
  project/DB/airflow/dags/03_cpi_pce.py
Labels: 🔧 개발 중

#344 tmp 수정
  project/DB/airflow/dags/03_cpi_pce.py
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/veiws_cautions_map.py
  project/WEB/chatbot/views_card_sales.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_main.py
  project/WEB/chatbot/views_tour.py
Labels: 🔧 개발 중

#345 revise dags_law data
  project/DB/airflow/dags/02_Korean_Law_data.py
  project/DB/airflow/dags/05_Currency_Forecast.py
Labels: 🐛 버그 🐛

#354 add card_sales_visualization
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/views_card_sales.py
  project/WEB/chatbot/views_main.py
Labels: 🔧 개발 중

#355 combined macro chart in ONE CARD
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/views_card_sales.py
Labels: 🔧 개발 중

#356 changed name on macro chart
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/views_fred.py
Labels: 🔧 개발 중

#357 plotly chart graphs fixed
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/veiws_cautions_map.py
  project/WEB/chatbot/views_card_sales.py
  project/WEB/chatbot/views_chatbot.py
  project/WEB/chatbot/views_fred.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_law.py
  project/WEB/chatbot/views_main.py
  project/WEB/chatbot/views_tour.py
  project/WEB/chatbot/views_travel_trend.py
  project/WEB/dashboards/watching_word.py
Labels: 🚧 기능 개발, 🔧 개발 중

#362 tmp origin.py 수정거시경제 dash 연습
  project/WEB/authenticate/urls.py
  project/WEB/authenticate/views.py
  project/WEB/chatbot/templates/tmp_origin.html
  project/WEB/chatbot/views_main.py
Labels: 🔧 개발 중

#364 env settings
  project/WEB/chatbot/views_law.py
  project/WEB/dashboards/es_service.py
Labels: 🐛 버그 🐛, 🚧 기능 개발, 🔧 개발 중

#369 revise currecny dags
  project/DB/airflow/dags/04_cuurency_rate.py
  project/DB/airflow/dags/07_cuurency_rate.py
Labels: ✅ 됐다!

#373 urls.py 연동
  project/WEB/chatbot/templates/tmp_origin.html
  project/WEB/chatbot/urls.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_main.py
Labels: ✅ 됐다!

#377 layout django update tmp
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/views_card_sales.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_main.py
  project/WEB/requirements.txt
Labels: 🐛 버그 🐛, 🚧 기능 개발, 🔧 개발 중

#383 Structure completed
  project/WEB/chatbot/templates/tmp.html
Labels: 🚧 기능 개발, ✅ 됐다!, 🔧 개발 중

#378 modified fred_data with sql query
  project/WEB/chatbot/templates/main.html
  project/WEB/chatbot/views_fred.py
  project/WEB/chatbot/views_main.py
Labels: ✅ 됐다!, 🔧 개발 중

#386 tmp_origin_indicator
  project/WEB/chatbot/templates/tmp_origin.html
  project/WEB/chatbot/views_fred.py
  project/WEB/chatbot/views_indicator.py
  project/WEB/chatbot/views_main.py
Labels: 🔧 개발 중

#387 layout change
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/views_currency.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_indicator.py
  project/WEB/chatbot/views_main.py
Labels: 🚧 기능 개발, 🔧 개발 중

#390 389 cpi pce index making
  project/DB/airflow/dags/03_cpi_pce.py
  project/WEB/chatbot/templates/tmp_origin.html
  project/WEB/chatbot/urls.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_indicator.py
  project/WEB/chatbot/views_main.py
Labels: ✅ 됐다!

#394 fin
  project/WEB/chatbot/templates/tmp.html
Labels: ✅ 됐다!

#402 Successfully connected the OpenAI API with the frontend for summariza…
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/views_chatbot.py
  project/WEB/chatbot/views_main.py
Labels: 🚧 기능 개발

#404 modified prompt
  project/WEB/chatbot/views_chatbot.py
Labels: 🚧 기능 개발, 🔧 개발 중

#405 Merge and refactoring Code for Django including dashboards, insights and chatbot
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/veiws_cautions_map.py
  project/WEB/chatbot/views_card_sales.py
  project/WEB/chatbot/views_fred.py
  project/WEB/chatbot/views_hoseop.py
  project/WEB/chatbot/views_indicator.py
  project/WEB/chatbot/views_main.py
  project/WEB/chatbot/views_tour.py
  project/WEB/chatbot/views_travel_trend.py
  project/WEB/docker-compose.yml
  project/WEB/staticfiles/js/chatbot.js
  project/WEB/staticfiles/js/dashboard.js
  project/WEB/staticfiles/js/insight.js
  project/WEB/woodjango/settings.py
Labels: 🚧 기능 개발, ✅ 됐다!, 🔧 개발 중

#411 bank_rate_dag
  project/DB/airflow/dags/13_bank_rate.py
Labels: ✅ 됐다!

#412 revise dags
  project/DB/airflow/Dockerfile
  project/DB/airflow/dags/13_bank_rate.py
Labels: ✅ 됐다!

#413 dag 수정
  project/DB/airflow/dags/13_bank_rate.py
Labels: ✅ 됐다!

#430 revise chatbot
  project/DB/airflow/Dockerfile
  project/DB/airflow/dags/09_eunchai_trend.py
  project/WEB/chatbot/views_chatbot.py
Labels: 🔧 개발 중

#431 히스토리 작업중
  project/WEB/authenticate/views.py
  project/WEB/chatbot/models.py
  project/WEB/chatbot/urls.py
  project/WEB/woodjango/settings.py
Labels: ✅ 됐다!

#435 update
  project/WEB/chatbot/templates/tmp.html
  project/WEB/chatbot/views_chatbot.py
Labels: ✅ 됐다!

#440 upgrade chatbot
  project/WEB/chatbot/views_chatbot.py
Labels: ✅ 됐다!
